-- ============================================================
-- HORIANT — Seed Data: 15 Luxury Watches
-- Run this in Supabase SQL Editor (Dashboard → SQL)
-- (Run AFTER 001_initial_schema.sql)
-- ============================================================

-- Clear existing seed data (safe to re-run)
DELETE FROM public.watches WHERE slug IN (
  'rolex-submariner', 'omega-speedmaster', 'patek-nautilus',
  'lange-datograph', 'grand-seiko-snowflake', 'jlc-reverso',
  'ap-royal-oak', 'cartier-santos', 'tudor-black-bay-58',
  'iwc-big-pilot', 'breitling-navitimer', 'rolex-gmt-pepsi',
  'vc-overseas', 'blancpain-fifty-fathoms', 'panerai-luminor'
);

INSERT INTO public.watches (
  brand, model, reference, year, caliber, power_reserve,
  case_size, lug_to_lug, thickness, material, water_resistance,
  crystal, bracelet, story_text, image_url, category, price,
  market_trend, transactions, rating, frequency, jewels,
  chrono24_url, complications, slug, is_featured
) VALUES

-- ─── 1. A. Lange & Söhne Datograph (FEATURED) ──────────────
(
  'A. Lange & Söhne',
  'Datograph',
  '403.035',
  2019,
  'L951.6',
  '60 Hours',
  '41.0 mm',
  '47.0 mm',
  '13.1 mm',
  'Platinum 950',
  '30 m',
  'Sapphire',
  'Alligator Leather',
  'First unveiled in 1999, the Datograph redefined what a German chronograph could be. Its column-wheel flyback mechanism, designed entirely in-house by Lange master watchmakers, immediately established the Saxon manufacture as a peer to the finest Swiss houses. The oversized date display — a Lange signature — and the perfectly symmetrical dial layout have made it one of the most coveted collector''s pieces of the 21st century. Each movement is assembled twice: once to test, then completely disassembled, cleaned, and rebuilt to final perfection.',
  'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800&q=80',
  'Chronograph',
  '$92,000',
  '+12.4%',
  24,
  5.0,
  '18,000 vph',
  '40',
  'https://www.chrono24.com/alangesohne/datograph--mod1163.htm',
  ARRAY['Flyback Chronograph', 'Big Date', 'Power Reserve'],
  'lange-datograph',
  true
),

-- ─── 2. Rolex Submariner Date ───────────────────────────────
(
  'Rolex',
  'Submariner Date',
  '126610LN',
  2023,
  'Cal. 3235',
  '70 Hours',
  '41.0 mm',
  '47.5 mm',
  '12.7 mm',
  'Oystersteel',
  '300 m',
  'Sapphire (Cyclops)',
  'Oyster / Oystersteel',
  'Born in 1953 as the world''s first divers'' watch waterproof to 100 metres, the Submariner defined an entire category of timepiece. It has accompanied explorers to the ocean floor and secret agents to the silver screen. Six decades of continuous evolution have refined every detail — from the Cerachrom bezel to the Glidelock clasp — while its essential character remains unchanged: the quintessential tool watch.',
  'https://images.unsplash.com/photo-1623998021446-45cd9b269c95?w=800&q=80',
  'Diver',
  '$14,200',
  '+3.6%',
  214,
  4.7,
  '28,800 vph',
  '31',
  'https://www.chrono24.com/rolex/submariner-date--mod79.htm',
  ARRAY['Date', 'Rotating Bezel'],
  'rolex-submariner',
  false
),

-- ─── 3. Omega Speedmaster Professional ──────────────────────
(
  'Omega',
  'Speedmaster Professional',
  '310.30.42.50.01.001',
  2024,
  'Cal. 3861',
  '50 Hours',
  '42.0 mm',
  '47.0 mm',
  '13.2 mm',
  'Stainless Steel',
  '50 m',
  'Hesalite',
  'Stainless Steel',
  'On July 20, 1969, Buzz Aldrin stepped onto the lunar surface with a Speedmaster strapped to his wrist over his spacesuit. That moment immortalised this chronograph as the Moonwatch — the only watch flight-qualified by NASA for extravehicular activity. The modern Cal. 3861 movement maintains the hand-wound soul that collectors revere while adding a co-axial escapement and Master Chronometer certification.',
  'https://images.unsplash.com/photo-1620625515032-6ed0c1790c75?w=800&q=80',
  'Chronograph',
  '$6,500',
  '+2.1%',
  178,
  4.8,
  '21,600 vph',
  '26',
  'https://www.chrono24.com/omega/speedmaster-professional-moonwatch--mod174.htm',
  ARRAY['Chronograph', 'Tachymeter'],
  'omega-speedmaster',
  false
),

-- ─── 4. Patek Philippe Nautilus 5711/1A ─────────────────────
(
  'Patek Philippe',
  'Nautilus 5711/1A',
  '5711/1A-010',
  2021,
  'Cal. 26-330 S C',
  '45 Hours',
  '40.0 mm',
  '44.6 mm',
  '8.3 mm',
  'Stainless Steel',
  '120 m',
  'Sapphire',
  'Integrated Steel',
  'Gérald Genta sketched the Nautilus on a napkin in 1976, and in doing so, invented the luxury sports watch category. Inspired by a ship''s porthole, its distinctive octagonal bezel and horizontally embossed dial broke every rule of haute horlogerie — and rewrote them. The 5711/1A, discontinued in 2021, has become the single most coveted reference in modern watchmaking, with waitlists stretching into legend.',
  'https://images.unsplash.com/photo-1594576722512-582bcd46fba3?w=800&q=80',
  'Dress',
  '$148,500',
  '+8.2%',
  89,
  4.9,
  '28,800 vph',
  '29',
  'https://www.chrono24.com/patekphilippe/nautilus--mod34.htm',
  ARRAY['Date', 'Sweep Seconds'],
  'patek-nautilus',
  false
),

-- ─── 5. Grand Seiko Snowflake SBGA211 ───────────────────────
(
  'Grand Seiko',
  'Snowflake SBGA211',
  'SBGA211',
  2022,
  'Cal. 9R65',
  '72 Hours',
  '41.0 mm',
  '48.0 mm',
  '12.5 mm',
  'Titanium',
  '100 m',
  'Sapphire (Dual-Curved)',
  'Titanium',
  'The Snowflake''s textured dial is not stamped, pressed, or printed. It is hand-finished through a process inspired by the deep, powdery snow of the Shinshu mountains visible from Grand Seiko''s Studio Shizukuishi. Beneath its surface lies the Spring Drive caliber 9R65 — a movement that exists in a category of one, combining a mainspring with a tri-synchro regulator for the smoothest sweep hand in all of horology.',
  'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800&q=80',
  'Dress',
  '$5,800',
  '+2.9%',
  156,
  4.8,
  '28,800 vph',
  '30',
  'https://www.chrono24.com/grandseiko/ref-sbga211.htm',
  ARRAY['Date', 'Power Reserve Indicator'],
  'grand-seiko-snowflake',
  false
),

-- ─── 6. Jaeger-LeCoultre Reverso Classic ────────────────────
(
  'Jaeger-LeCoultre',
  'Reverso Classic',
  'Q3858520',
  2020,
  'Cal. 822/2',
  '42 Hours',
  '45.6 × 27.4 mm',
  '45.6 mm',
  '9.1 mm',
  'Stainless Steel',
  '30 m',
  'Sapphire',
  'Alligator Leather',
  'Created in 1931 for British polo officers in colonial India who needed a watch that could survive a chukker, the Reverso''s reversible case is one of the most iconic industrial designs of the Art Deco era. The blank caseback was originally meant to shield the crystal from mallet blows — today, it invites personal engravings and, in dual-face models, a second time zone.',
  'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=800&q=80',
  'Dress',
  '$5,500',
  '+1.8%',
  132,
  4.6,
  '21,600 vph',
  '19',
  'https://www.chrono24.com/jaegerlecoultre/reverso--mod22.htm',
  ARRAY['Small Seconds'],
  'jlc-reverso',
  false
),

-- ─── 7. Audemars Piguet Royal Oak "Jumbo" ───────────────────
(
  'Audemars Piguet',
  'Royal Oak "Jumbo"',
  '16202ST.OO.1240ST.01',
  2022,
  'Cal. 7121',
  '55 Hours',
  '39.0 mm',
  '44.5 mm',
  '8.1 mm',
  'Stainless Steel',
  '50 m',
  'Sapphire',
  'Integrated Steel',
  'Another Gérald Genta masterwork, the Royal Oak debuted at Baselworld 1972 and scandalised the industry: a stainless steel watch priced above gold. Its octagonal bezel with eight hexagonal screws, integrated bracelet, and Petite Tapisserie dial became the template for luxury sports watchmaking.',
  'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=800&q=80',
  'Dress',
  '$72,000',
  '+5.4%',
  67,
  4.9,
  '28,800 vph',
  '37',
  'https://www.chrono24.com/audemarspiguet/royal-oak--mod24.htm',
  ARRAY['Date'],
  'ap-royal-oak',
  false
),

-- ─── 8. Cartier Santos de Cartier ───────────────────────────
(
  'Cartier',
  'Santos de Cartier',
  'WSSA0018',
  2023,
  'Cal. 1847 MC',
  '42 Hours',
  '39.8 mm',
  '47.5 mm',
  '9.1 mm',
  'Stainless Steel',
  '100 m',
  'Sapphire',
  'Steel / Alligator QuickSwitch',
  'In 1904, Louis Cartier created a wristwatch for his friend Alberto Santos-Dumont, who needed to check the time while flying his dirigible. The result was the Santos — widely regarded as the first purpose-built men''s wristwatch. Its exposed screws, Roman numeral dial, and square case anticipated the Art Deco movement by two decades.',
  'https://images.unsplash.com/photo-1627037558426-c2d07beda3af?w=800&q=80',
  'Dress',
  '$7,650',
  '+1.2%',
  198,
  4.5,
  '28,800 vph',
  '25',
  'https://www.chrono24.com/cartier/santos-de-cartier--mod5349.htm',
  ARRAY['Date'],
  'cartier-santos',
  false
),

-- ─── 9. Tudor Black Bay 58 ──────────────────────────────────
(
  'Tudor',
  'Black Bay 58',
  'M79030N-0001',
  2023,
  'Cal. MT5402',
  '70 Hours',
  '39.0 mm',
  '47.8 mm',
  '11.9 mm',
  'Stainless Steel',
  '200 m',
  'Sapphire',
  'Steel / Riveted',
  'The Black Bay 58 distills six decades of Tudor''s dive watch heritage into a case that wears like a vintage reference. Named after the year Tudor introduced its first diver with a crown guard, the BB58 swaps modern bulk for slim, wrist-hugging proportions. Powered by the COSC-certified MT5402 in-house caliber with 70 hours of power reserve.',
  'https://images.unsplash.com/photo-1585123334904-845d60e97b29?w=800&q=80',
  'Diver',
  '$3,575',
  '+1.5%',
  312,
  4.6,
  '28,800 vph',
  '26',
  'https://www.chrono24.com/tudor/black-bay-58--mod3988.htm',
  ARRAY['Date', 'Rotating Bezel'],
  'tudor-black-bay-58',
  false
),

-- ─── 10. IWC Big Pilot's Watch 43 ──────────────────────────
(
  'IWC',
  'Big Pilot''s Watch 43',
  'IW329301',
  2023,
  'Cal. 82100',
  '60 Hours',
  '43.0 mm',
  '52.0 mm',
  '13.6 mm',
  'Stainless Steel',
  '100 m',
  'Sapphire (AR-coated)',
  'Stainless Steel / EasX-CHANGE',
  'IWC''s Big Pilot lineage stretches back to the massive 55mm observation watches built for the Luftwaffe in 1940. The modern Big Pilot''s Watch 43 refines that DNA into a more wearable package without sacrificing the commanding dial presence — oversized Arabic numerals, a conical crown designed for gloved hands, and a soft-iron inner case for antimagnetic protection.',
  'https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80',
  'Pilot',
  '$8,900',
  '+1.9%',
  145,
  4.5,
  '28,800 vph',
  '33',
  'https://www.chrono24.com/iwc/big-pilots-watch--mod216.htm',
  ARRAY['Date', 'Power Reserve'],
  'iwc-big-pilot',
  false
),

-- ─── 11. Breitling Navitimer B01 ────────────────────────────
(
  'Breitling',
  'Navitimer B01 Chronograph 43',
  'AB0138211B1A1',
  2023,
  'Cal. B01',
  '70 Hours',
  '43.0 mm',
  '48.3 mm',
  '13.6 mm',
  'Stainless Steel',
  '30 m',
  'Sapphire (AR-coated)',
  'Stainless Steel / Navitimer',
  'Introduced in 1952, the Navitimer was originally designed as a wrist-mounted flight computer for the Aircraft Owners and Pilots Association. Its iconic circular slide rule bezel allows pilots to calculate fuel consumption, climb rates, and ground speed. The B01 in-house movement brought Breitling''s most famous model back under its own horological roof with a column-wheel chronograph.',
  'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800&q=80',
  'Chronograph',
  '$9,100',
  '+2.3%',
  167,
  4.4,
  '28,800 vph',
  '47',
  'https://www.chrono24.com/breitling/navitimer--mod19.htm',
  ARRAY['Chronograph', 'Slide Rule Bezel', 'Date'],
  'breitling-navitimer',
  false
),

-- ─── 12. Rolex GMT-Master II "Pepsi" ────────────────────────
(
  'Rolex',
  'GMT-Master II "Pepsi"',
  '126710BLRO',
  2023,
  'Cal. 3285',
  '70 Hours',
  '40.0 mm',
  '47.5 mm',
  '12.1 mm',
  'Oystersteel',
  '100 m',
  'Sapphire (Cyclops)',
  'Jubilee / Oystersteel',
  'Pan Am commissioned Rolex to build a watch for its transatlantic pilots in 1955, and the GMT-Master was born — with its signature two-tone bezel enabling simultaneous tracking of home and destination time zones. The red-and-blue "Pepsi" colorway has become the most iconic bezel combination in watchmaking history. The modern 126710BLRO pairs a Cerachrom bezel with the Jubilee bracelet.',
  'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=800&q=80',
  'GMT',
  '$20,800',
  '+6.1%',
  189,
  4.8,
  '28,800 vph',
  '31',
  'https://www.chrono24.com/rolex/gmt-master-ii--mod82.htm',
  ARRAY['GMT', 'Date', 'Rotating Bezel'],
  'rolex-gmt-pepsi',
  false
),

-- ─── 13. Vacheron Constantin Overseas ───────────────────────
(
  'Vacheron Constantin',
  'Overseas',
  '4500V/110A-B483',
  2022,
  'Cal. 5100',
  '60 Hours',
  '41.0 mm',
  '47.5 mm',
  '11.0 mm',
  'Stainless Steel',
  '150 m',
  'Sapphire (AR-coated)',
  'Steel / Rubber / Leather (interchangeable)',
  'Founded in 1755, Vacheron Constantin is the oldest continuously operating watchmaker in the world. The Overseas is the Maison''s answer to the luxury sports watch — a Maltese cross-inspired bezel, integrated bracelet, and a travel-ready interchangeable strap system with an in-house COSC-certified movement.',
  'https://images.unsplash.com/photo-1606744824163-985d376605aa?w=800&q=80',
  'Dress',
  '$24,500',
  '+3.8%',
  78,
  4.7,
  '28,800 vph',
  '27',
  'https://www.chrono24.com/vacheronconstantin/overseas--mod232.htm',
  ARRAY['Date', 'Sweep Seconds'],
  'vc-overseas',
  false
),

-- ─── 14. Blancpain Fifty Fathoms ────────────────────────────
(
  'Blancpain',
  'Fifty Fathoms',
  '5015-1130-52A',
  2023,
  'Cal. 1315',
  '120 Hours',
  '45.0 mm',
  '52.3 mm',
  '15.5 mm',
  'Stainless Steel',
  '300 m',
  'Sapphire (AR-coated)',
  'Sail Canvas / NATO',
  'In 1953, Captain Robert Maloubier of the French Navy''s combat swimmers needed a reliable dive watch. He approached Blancpain CEO Jean-Jacques Fiechter and together they created the Fifty Fathoms — the original modern dive watch. The cal. 1315 delivers an extraordinary five days of power reserve from three series-coupled barrels.',
  'https://images.unsplash.com/photo-1609587312208-cea54be969e7?w=800&q=80',
  'Diver',
  '$14,700',
  '+2.7%',
  98,
  4.6,
  '28,800 vph',
  '35',
  'https://www.chrono24.com/blancpain/fifty-fathoms--mod76.htm',
  ARRAY['Date', 'Rotating Bezel'],
  'blancpain-fifty-fathoms',
  false
),

-- ─── 15. Panerai Luminor Marina ─────────────────────────────
(
  'Panerai',
  'Luminor Marina',
  'PAM01312',
  2022,
  'Cal. P.9010',
  '72 Hours',
  '44.0 mm',
  '52.5 mm',
  '15.6 mm',
  'Stainless Steel',
  '300 m',
  'Sapphire',
  'Rubber / Alligator Leather',
  'Panerai''s history is rooted in secrecy. Originally a supplier to the Italian Navy''s elite frogmen during World War II, the Luminor''s iconic crown-protecting bridge device was designed to ensure waterproof integrity during underwater demolition missions. The sandwich dial was created for maximum legibility in zero-visibility waters. Today, it is the most recognizable Italian watch in the world.',
  'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800&q=80',
  'Diver',
  '$8,900',
  '+1.4%',
  134,
  4.4,
  '28,800 vph',
  '28',
  'https://www.chrono24.com/panerai/luminor-marina--mod169.htm',
  ARRAY['Date', 'Small Seconds'],
  'panerai-luminor',
  false
);

-- Verify the seed
SELECT brand, model, slug, category, is_featured FROM public.watches ORDER BY brand;
